In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report
import json
from tqdm.notebook import tqdm
from mqt import qcec
from qiskit import QuantumCircuit, transpile
from qiskit_aer import Aer
from scipy.stats import chisquare
from mqt import qcec
import requests
from qiskit.quantum_info import Statevector
from qiskit.quantum_info.operators.predicates import matrix_equal
import matplotlib.pyplot as plt
import qiskit as qk
try: 
    from BeautifulSoup import BeautifulSoup
except ImportError:
    from bs4 import BeautifulSoup
ideal_simulator = Aer.get_backend('qasm_simulator')

In [2]:
def load_program(name):
    
    qc = QuantumCircuit.from_qasm_file("benchmarkFilteration/benchmark/{}".format(name))
    qc.remove_final_measurements()
    if len(qc.clbits)>0:
        for i in range(len(qc.clbits)):
            qc.measure(i,i)
    else:
        qc.measure_all()
        
    return qc.copy()


def load_mutants(name):
    
    qc_list = []
    for mutant in sorted(os.listdir("benchmarkFilteration/mutants/mutants_{}/".format(name.replace(".qasm","")))):
        qc = QuantumCircuit.from_qasm_file("benchmarkFilteration/mutants/mutants_{}/{}".format(name.replace(".qasm",""),mutant))
        qc.remove_final_measurements()
        if len(qc.clbits)>0:
            for i in range(len(qc.clbits)):
                qc.measure(i,i)
        else:
            qc.measure_all()
        
        qc_list.append(qc.copy())
        
    return qc_list

def load_program_mutant_mix(name):
    program_name = name.replace("_mutant_","&").split("&")[0]
    mutant_number = name.split("_")[-1]
    program = "benchmarkFilteration/benchmark/"+program_name+".qasm"
    mutant_name = sorted(os.listdir(f"benchmarkFilteration/mutants/mutants_{program_name}/"))[int(mutant_number)-1]
    mutant = f"benchmarkFilteration/mutants/mutants_{program_name}/"+mutant_name
    return program,mutant
    

def get_ps(qc,simulator,prob=True):
    
    counts = simulator.run(transpile(qc,basis_gates=simulator.operation_names,
                                     optimization_level=0,seed_transpiler=42),
                           shots=4000,seed_simulator=42).result().get_counts()
    if isinstance(counts,list):
        PS = []
        for count in counts:
            temp = dict(sorted(count.items(),key=lambda x: int(x[0],2)))
            if prob:
                for k in temp.keys():
                    temp[k] = temp[k]/4000
            PS.append(temp)
        return PS
    else:
        ps = dict(sorted(counts.items(),key=lambda x: int(x[0],2)))
        if prob:
            for k in ps.keys():
                ps[k] = ps[k]/4000
        return ps
    
def qucat_oracle(ps,observed):
    A = set(ps.keys())
    B = set(observed.keys())
    if len(A.difference(B))!=0 or len(B.difference(A))!=0:
        return 0
    else:
        _,pvalue = chisquare(list(observed.values()),list(ps.values()))
        if pvalue<0.01:
            return 0
        else:
            return 1
        
def add_input(circ,inp):
    new_circ = QuantumCircuit(circ.num_qubits)
    for i,v in enumerate(inp):
        if v=="1":
            new_circ.x(i)
    
    new_circ = new_circ.compose(circ)
    new_circ.remove_final_measurements()
    if len(new_circ.clbits)>0:
        for i in range(len(new_circ.clbits)):
            new_circ.measure(i,i)
    else:
        new_circ.measure_all()
        
    return new_circ

def change_to_Hbasis(circ):
    new_circ = circ.copy()
    new_circ.remove_final_measurements()
    for i in range(new_circ.num_qubits):
        new_circ.h(i)
    if len(new_circ.clbits)>0:
        for i in range(len(new_circ.clbits)):
            new_circ.measure(i,i)
    else:
        new_circ.measure_all()
    return new_circ

def change_to_Ybasis(circ):
    new_circ = circ.copy()
    new_circ.remove_final_measurements()
    for i in range(new_circ.num_qubits):
        new_circ.sdg(i)
        new_circ.h(i)
    if len(new_circ.clbits)>0:
        for i in range(len(new_circ.clbits)):
            new_circ.measure(i,i)
    else:
        new_circ.measure_all()
    return new_circ
    

def perf_measure(y_actual, y_hat):
    TP = 0
    FP = 0
    TN = 0
    FN = 0

    for i in range(len(y_hat)): 
        if y_actual[i]==y_hat[i]==1:
            TP += 1
        if y_hat[i]==1 and y_actual[i]!=y_hat[i]:
            FP += 1
        if y_actual[i]==y_hat[i]==0:
            TN += 1
        if y_hat[i]==0 and y_actual[i]!=y_hat[i]:
            FN += 1

    return(TP, FP, TN, FN)

def add_Qinput(circ,mcirc):
    res = requests.post(url="http://13.54.252.151:30003/",data={"number":circ.num_qubits,"method":"UCNOT"})
    parsed_html = BeautifulSoup(res.text)
    inp = parsed_html.body.find('h4', attrs={'class':'text-center my-4'}).text
    
    new_circ = QuantumCircuit.from_qasm_str(inp)
    new_circ = new_circ.compose(circ)
    new_circ.remove_final_measurements()
    if len(new_circ.clbits)>0:
        for i in range(len(new_circ.clbits)):
            new_circ.measure(i,i)
    else:
        new_circ.measure_all()
        
    new_mcirc = QuantumCircuit.from_qasm_str(inp)
    new_mcirc = new_mcirc.compose(mcirc)
    new_mcirc.remove_final_measurements()
    if len(new_mcirc.clbits)>0:
        for i in range(len(new_mcirc.clbits)):
            new_mcirc.measure(i,i)
    else:
        new_mcirc.measure_all()
    
        
    return new_circ,new_mcirc

In [3]:
ground,qpredicted,hpredicted = [],[],[]
for files in tqdm(os.listdir("ground_truth/")):
    file = open("ground_truth/"+files,"r")
    data = json.load(file)
    file.close()
    for k,v in data.items():
        ground.append(v)


for files in tqdm(os.listdir("hamiltonian_result/")):
    file = open("hamiltonian_result/"+files,"r")
    data = json.load(file)
    file.close()
    for k,v in data.items():
        qpredicted.append(v["qucat_oracle"])
        hpredicted.append(v["ham_oracle"])

  0%|          | 0/157 [00:00<?, ?it/s]

  0%|          | 0/157 [00:00<?, ?it/s]

In [4]:
df = pd.DataFrame()
df["ground"] = ground
df["ETO"] = qpredicted
df["QOPS"] = hpredicted
df

        ground  ETO  QOPS
0            0    0     0
1            0    0     0
2            0    0     0
3            0    0     0
4            0    0     0
...        ...  ...   ...
194977       0    0     0
194978       0    0     0
194979       0    0     0
194980       0    0     0
194981       0    0     0

[194982 rows x 3 columns]

In [6]:
faulty_class = df[df["ground"]==0]
equivalent_class = df[df["ground"]==1]

In [7]:
print("------------------Old Oracle Faulty-----------------")
print(classification_report(faulty_class["ground"].values,faulty_class["ETO"].values,digits=3))
print("------------------Hamiltonian Faulty------------------\n")
print(classification_report(faulty_class["ground"].values,faulty_class["QOPS"].values,digits=3))

------------------Old Oracle Faulty-----------------
              precision    recall  f1-score   support

           0      1.000     0.997     0.999    164898
           1      0.000     0.000     0.000         0

    accuracy                          0.997    164898
   macro avg      0.500     0.499     0.499    164898
weighted avg      1.000     0.997     0.999    164898

------------------Hamiltonian Faulty------------------

C:\DATA\anaconda3\envs\quota\lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\DATA\anaconda3\envs\quota\lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\DATA\anaconda3\envs\quota\lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0      1.000     1.000     1.000    164898

    accuracy                          1.000    164898
   macro avg      1.000     1.000     1.000    164898
weighted avg      1.000     1.000     1.000    164898

In [9]:
TP, FN, TN, FP = perf_measure(faulty_class["ground"].values,faulty_class["ETO"].values)
print(TP,FN,TN,FP)

0 484 164414 0

In [12]:
print("------------------Old Oracle EQ-----------------")
print(classification_report(equivalent_class["ground"].values,equivalent_class["ETO"].values,digits=8))
print("------------------Hamiltonian EQ------------------\n")
print(classification_report(equivalent_class["ground"].values,equivalent_class["QOPS"].values,digits=8))

------------------Old Oracle EQ-----------------
              precision    recall  f1-score   support

           0  0.00000000 0.00000000 0.00000000         0
           1  1.00000000 0.99983380 0.99991689     30084

    accuracy                      0.99983380     30084
   macro avg  0.50000000 0.49991690 0.49995845     30084
weighted avg  1.00000000 0.99983380 0.99991689     30084

------------------Hamiltonian EQ------------------

              precision    recall  f1-score   support

           1  1.00000000 1.00000000 1.00000000     30084

    accuracy                      1.00000000     30084
   macro avg  1.00000000 1.00000000 1.00000000     30084
weighted avg  1.00000000 1.00000000 1.00000000     30084

C:\DATA\anaconda3\envs\quota\lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\DATA\anaconda3\envs\quota\lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\DATA\anaconda3\envs\quota\lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [11]:
TP, FN, TN, FP = perf_measure(equivalent_class["ground"].values,equivalent_class["ETO"].values)
print(TP,FN,TN,FP)

30079 0 0 5

# Case 1 (Q=0, G=1)  i.e False Positives

In [5]:
TP, FN, TN, FP = perf_measure(ground,qpredicted)
case1_percentage = round(FP/len(ground)*100,2)

In [6]:
print(f"{case1_percentage = }\ni.e from {len(ground)} only {FP}")

case1_percentage = 0.0
i.e from 194982 only 5

# Case 1 (H=0, G=1)  i.e False Positives

In [7]:
TP, FN, TN, FP = perf_measure(ground,hpredicted)
case1_percentage = round(FP/len(ground)*100,2)

In [8]:
print(f"{case1_percentage = }\ni.e from {len(ground)} only {FP}")

case1_percentage = 0.0
i.e from 194982 only 0

# Case 2 (Q=1, G=0) False Negatives

In [9]:
TP, FN, TN, FP = perf_measure(ground,qpredicted)
case2_percentage = round(FN/len(ground)*100,2)

In [10]:
print(f"{case2_percentage = }\ni.e from {len(ground)} only {FN}")

case2_percentage = 0.25
i.e from 194982 only 484

# Case 2 (H=1, G=0) False Negatives

In [11]:
TP, FN, TN, FP = perf_measure(ground,hpredicted)
case2_percentage = round(FN/len(ground)*100,2)

In [12]:
print(f"{case2_percentage = }\ni.e from {len(ground)} only {FN}")

case2_percentage = 0.0
i.e from 194982 only 0

# Mutation Score analysis

In [13]:
result = {"program":[],"qubits":[],"Q":[],"H":[],"Total":[]}
for files in tqdm(os.listdir("hamiltonian_result/")):
    file = open("hamiltonian_result/"+files,"r")
    data = json.load(file)
    file.close()
    qscore = 0
    hscore = 0
    
    for k,v in data.items():
        if v["qucat_oracle"]==0:
            qscore+=1
        if v["ham_oracle"]==0:
            hscore+=1
    
    file = open("ground_truth/"+files,"r")
    gr = json.load(file)
    file.close()
    total = len([gr[x] for x in gr.keys() if gr[x]==0])
    
    result["program"].append(files.split("_")[0])
    result["Q"].append(qscore)
    result["H"].append(hscore)
    result["Total"].append(total)
    result["qubits"].append(files.split("_")[-1].replace(".json",""))

  0%|          | 0/157 [00:00<?, ?it/s]

In [14]:
data = pd.DataFrame.from_dict(result)
program_group = data.groupby("program")
data["Q_score"] = (data["Q"]/data["Total"])*100
data["H_score"] = (data["H"]/data["Total"])*100
data = data.round(2)
data

    program qubits     Q     H  Total  Q_score  H_score
0        ae     10  1950  1950   1950   100.00    100.0
1        ae      2   143   143    143   100.00    100.0
2        ae      3   291   291    291   100.00    100.0
3        ae      4   459   459    459   100.00    100.0
4        ae      5   648   649    649    99.85    100.0
..      ...    ...   ...   ...    ...      ...      ...
152  wstate      5   302   302    302   100.00    100.0
153  wstate      6   371   371    371   100.00    100.0
154  wstate      7   446   446    446   100.00    100.0
155  wstate      8   520   520    520   100.00    100.0
156  wstate      9   593   594    594    99.83    100.0

[157 rows x 7 columns]

In [15]:
print(data[data["Q_score"]>data["H_score"]].shape[0])
data[data["Q_score"]>data["H_score"]]

3

    program qubits    Q    H  Total  Q_score  H_score
141     vqe      3  277  274    274   101.09    100.0
142     vqe      4  372  371    371   100.27    100.0
143     vqe      5  442  441    441   100.23    100.0

In [16]:
print(data[data["Q_score"]<data["H_score"]].shape[0])
data[data["Q_score"]<data["H_score"]]

37

            program qubits     Q     H  Total  Q_score  H_score
4                ae      5   648   649    649    99.85    100.0
18              ghz     10   140   188    188    74.47    100.0
19              ghz      2    22    23     23    95.65    100.0
20              ghz      3    36    43     43    83.72    100.0
21              ghz      4    51    68     68    75.00    100.0
23              ghz      6    82   108    108    75.93    100.0
24              ghz      7    96   130    130    73.85    100.0
25              ghz      8   110   145    145    75.86    100.0
26              ghz      9   125   163    163    76.69    100.0
28       graphstate      3    42    64     64    65.62    100.0
29       graphstate      4    56    88     88    63.64    100.0
30       graphstate      5    72   117    117    61.54    100.0
36    portfolioqaoa      3   459   461    461    99.57    100.0
37    portfolioqaoa      4   723   733    733    98.64    100.0
39    portfolioqaoa      6  1500  1514   1514    99.08    100.0
40    portfolioqaoa      7  1968  1987   1987    99.04    100.0
41    portfolioqaoa      8  2544  2545   2545    99.96    100.0
44     portfoliovqe      3   442   446    446    99.10    100.0
45     portfoliovqe      4   718   722    722    99.45    100.0
46     portfoliovqe      5  1078  1080   1080    99.81    100.0
47     portfoliovqe      6  1468  1480   1480    99.19    100.0
69              qft      2    28    30     30    93.33    100.0
82              qnn      6  2610  2619   2619    99.66    100.0
99       qpeinexact      5   367   368    368    99.73    100.0
105          random      2   303   307    307    98.70    100.0
107          random      4   872   874    874    99.77    100.0
116   realamprandom      4   697   728    728    95.74    100.0
118   realamprandom      6  1507  1509   1509    99.87    100.0
123       su2random      2   222   231    231    96.10    100.0
125       su2random      4   747   748    748    99.87    100.0
126       su2random      5  1077  1088   1088    98.99    100.0
127       su2random      6  1525  1526   1526    99.93    100.0
134  twolocalrandom      4   705   734    734    96.05    100.0
136  twolocalrandom      6  1518  1519   1519    99.93    100.0
140             vqe     10   915   920    920    99.46    100.0
148          wstate     10   668   669    669    99.85    100.0
156          wstate      9   593   594    594    99.83    100.0

In [17]:
sum_data = program_group.sum()
sum_data["Q_score"] = (sum_data["Q"]/sum_data["Total"])*100
sum_data["H_score"] = (sum_data["H"]/sum_data["Total"])*100
sum_data = sum_data.drop(columns=["qubits"]).round(2)

In [18]:
sum_data.style.highlight_max(color='green',axis=1,subset=["Q_score","H_score"])